baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sofian Rahhali'
theme = 'PaperMod'

disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "#about"
	weight = 1

[[menu.main]]
	identifier = "education"
	name = "Education"
	url = "#education"
	weight = 10

[[menu.main]]
	identifier = "experience"
	name = "Experience"
	url = "#experience"
	weight = 20

[[menu.main]]
	identifier = "projects"
	name = "Projects"
	url = "#projects"
	weight = 30

[[menu.main]]
	identifier = "skills"
	name = "Skills"
	url = "#skills"
	weight = 40

[caches]
  [caches.images]
    dir = ':cacheDir/images'